### ISSUE TITLE
About behavior discriminator

### ISSUE THREAD

**Issue by xfleezy** [rddy/pico#1]
Hello, I'm a little confused about the behavior discrimination model in the paper. When T =1, the user observes the original image and takes action a. When T = 0, the user observes the compressed image and takes action a. So are there differences between the two actions? For example, in the MNIST dataset, what is action a when the user observed a compressed image of "6"? Thanks for your explanation. Your work is very elegant and inspired me a lot.

**Comment by rddy** [comment]
Thanks for your question. For both T=0 and T=1, the action a has the same type. For example, in the MNIST domain, the action a is a digit label from the set {0, 1, 2, ..., 9}.

**Comment by xfleezy** [comment]
Thanks for your answer.  For both T=0 and T=1, the action a has the same type. Does this mean the input image is different for T=0 and T=1? But it is mentioned in the paper that the behavior discriminator is only conditioned on the original image.

**Comment by rddy** [comment]
Yes, the input image is different. For T=0, the user observes the compressed image. For T=1, the user observes the original, uncompressed image. For both T=0 and T=1, the behavior discriminator is conditioned on the action and the original image, because we want to match the conditional distributions of actions given original images (see Equation 1 in the paper).
